/*
 * Generated by Bluespec Compiler, version 2025.01.1 (build 65e3a87)
 * 
 * On Mon Apr 14 11:14:53 IST 2025
 * 
 */

/* Generation options: */
#ifndef __model_mkRegisterFile_h__
#define __model_mkRegisterFile_h__

#include "bluesim_types.h"
#include "bs_module.h"
#include "bluesim_primitives.h"
#include "bs_vcd.h"

#include "bs_model.h"
#include "mkRegisterFile.h"

/* Class declaration for a model of mkRegisterFile */
class MODEL_mkRegisterFile : public Model {
 
 /* Top-level module instance */
 private:
  MOD_mkRegisterFile *mkRegisterFile_instance;
 
 /* Handle to the simulation kernel */
 private:
  tSimStateHdl sim_hdl;
 
 /* Constructor */
 public:
  MODEL_mkRegisterFile();
 
 /* Functions required by the kernel */
 public:
  void create_model(tSimStateHdl simHdl, bool master);
  void destroy_model();
  void reset_model(bool asserted);
  void get_version(char const **name, char const **build);
  time_t get_creation_time();
  void * get_instance();
  void dump_state();
  void dump_VCD_defs();
  void dump_VCD(tVCDDumpType dt);
};

/* Function for creating a new model */
extern "C" {
  void * new_MODEL_mkRegisterFile();
}

#endif /* ifndef __model_mkRegisterFile_h__ */
