//
// Generated by Bluespec Compiler, version 2025.01.1 (build 65e3a87)
//
// On Tue Apr  8 16:41:55 IST 2025
//
//
// Ports:
// Name                         I/O  size props
// leds                           O     8 reg
// RDY_leds                       O     1 const
// RDY_reset                      O     1 const
// CLK                            I     1 clock
// RST_N                          I     1 reset
// EN_reset                       I     1
//
// No combinational paths from inputs to outputs
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module mkLEDBlinkerTop(CLK,
		       RST_N,

		       leds,
		       RDY_leds,

		       EN_reset,
		       RDY_reset);
  input  CLK;
  input  RST_N;

  // value method leds
  output [7 : 0] leds;
  output RDY_leds;

  // action method reset
  input  EN_reset;
  output RDY_reset;

  // signals for module outputs
  wire [7 : 0] leds;
  wire RDY_leds, RDY_reset;

  // ports of submodule blinker
  wire [7 : 0] blinker$leds;
  wire blinker$EN_reset;

  // value method leds
  assign leds = blinker$leds ;
  assign RDY_leds = 1'd1 ;

  // action method reset
  assign RDY_reset = 1'd1 ;

  // submodule blinker
  mkLEDBlinker blinker(.CLK_clk(CLK),
		       .RST_N_rst(RST_N),
		       .CLK(CLK),
		       .RST_N(RST_N),
		       .EN_reset(blinker$EN_reset),
		       .leds(blinker$leds),
		       .RDY_leds(),
		       .RDY_reset());

  // submodule blinker
  assign blinker$EN_reset = EN_reset ;
endmodule  // mkLEDBlinkerTop

