//
// Generated by Bluespec Compiler, version 2025.01.1 (build 65e3a87)
//
// On Mon Mar 24 15:34:59 IST 2025
//
//
// Ports:
// Name                         I/O  size props
// RDY_set                        O     1 const
// get                            O     1 reg
// RDY_get                        O     1 const
// CLK                            I     1 clock
// RST_N                          I     1 reset
// set_d                          I     1 reg
// EN_set                         I     1
//
// No combinational paths from inputs to outputs
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module mkDFF(CLK,
	     RST_N,

	     set_d,
	     EN_set,
	     RDY_set,

	     get,
	     RDY_get);
  input  CLK;
  input  RST_N;

  // action method set
  input  set_d;
  input  EN_set;
  output RDY_set;

  // value method get
  output get;
  output RDY_get;

  // signals for module outputs
  wire RDY_get, RDY_set, get;

  // register q
  reg q;
  wire q$D_IN, q$EN;

  // action method set
  assign RDY_set = 1'd1 ;

  // value method get
  assign get = q ;
  assign RDY_get = 1'd1 ;

  // register q
  assign q$D_IN = set_d ;
  assign q$EN = EN_set ;

  // handling of inlined registers

  always@(posedge CLK)
  begin
    if (RST_N == `BSV_RESET_VALUE)
      begin
        q <= `BSV_ASSIGNMENT_DELAY 1'd0;
      end
    else
      begin
        if (q$EN) q <= `BSV_ASSIGNMENT_DELAY q$D_IN;
      end
  end

  // synopsys translate_off
  `ifdef BSV_NO_INITIAL_BLOCKS
  `else // not BSV_NO_INITIAL_BLOCKS
  initial
  begin
    q = 1'h0;
  end
  `endif // BSV_NO_INITIAL_BLOCKS
  // synopsys translate_on
endmodule  // mkDFF

