//
// Generated by Bluespec Compiler, version 2025.01.1 (build 65e3a87)
//
// On Mon Apr 14 00:54:43 IST 2025
//
//
// Ports:
// Name                         I/O  size props
// CLK                            I     1 clock
// RST_N                          I     1 reset
//
// No combinational paths from inputs to outputs
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module mkMultipleRile(CLK,
		      RST_N);
  input  CLK;
  input  RST_N;

  // register count
  reg [7 : 0] count;
  wire [7 : 0] count$D_IN;
  wire count$EN;

  // rule scheduling signals
  wire WILL_FIRE_RL_incIfOdd;

  // rule RL_incIfOdd
  assign WILL_FIRE_RL_incIfOdd = count[0] && count < 8'd20 ;

  // register count
  assign count$D_IN = count + 8'd1 ;
  assign count$EN = WILL_FIRE_RL_incIfOdd || !count[0] ;

  // handling of inlined registers

  always@(posedge CLK)
  begin
    if (RST_N == `BSV_RESET_VALUE)
      begin
        count <= `BSV_ASSIGNMENT_DELAY 8'd0;
      end
    else
      begin
        if (count$EN) count <= `BSV_ASSIGNMENT_DELAY count$D_IN;
      end
  end

  // synopsys translate_off
  `ifdef BSV_NO_INITIAL_BLOCKS
  `else // not BSV_NO_INITIAL_BLOCKS
  initial
  begin
    count = 8'hAA;
  end
  `endif // BSV_NO_INITIAL_BLOCKS
  // synopsys translate_on

  // handling of system tasks

  // synopsys translate_off
  always@(negedge CLK)
  begin
    #0;
    if (RST_N != `BSV_RESET_VALUE)
      if (!count[0]) $display("[incIfEven] count => %d", count);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_incIfOdd) $display("[incIfOdd] count => %d", count);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_incIfOdd && count == 8'd19) $finish(32'd1);
  end
  // synopsys translate_on
endmodule  // mkMultipleRile

